#!/usr/bin/env python3
from __future__ import annotations

import html
import json
import sys
from pathlib import Path


def _format_ops(value: float) -> str:
    if value >= 1_000_000_000:
        return f"{value / 1_000_000_000:.2f}B"
    if value >= 1_000_000:
        return f"{value / 1_000_000:.2f}M"
    if value >= 1_000:
        return f"{value / 1_000:.2f}K"
    return f"{value:.0f}"


def _format_ms(value: float) -> str:
    if value >= 100:
        return f"{value:.0f}"
    if value >= 10:
        return f"{value:.1f}"
    return f"{value:.3f}"


def _format_pct(value: float) -> str:
    return f"{value * 100:.2f}%"


def _status_style(status: str) -> tuple[str, str]:
    normalized = status.lower()
    if normalized == "ok":
        return "#10b981", "#ecfdf5"
    if normalized in {"warn", "warning", "degraded"}:
        return "#f59e0b", "#fffbeb"
    return "#ef4444", "#fef2f2"


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: bench/render_svg.py <input.json> <output.svg>", file=sys.stderr)
        return 1

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    data = json.loads(input_path.read_text())
    ops_per_sec = data.get("ops_per_sec")
    p99_ms = data.get("p99_ms")
    if ops_per_sec is None or p99_ms is None:
        raise SystemExit("Input JSON must include ops_per_sec and p99_ms")

    ops_label = _format_ops(float(ops_per_sec))
    p99_label = f"{float(p99_ms):.3f} ms"
    duration_ms = data.get("duration_ms")
    ops_total = data.get("ops_total")
    scenarios = data.get("scenarios")
    if not isinstance(scenarios, list) or not scenarios:
        raise SystemExit("Input JSON must include non-empty scenarios array")

    footer_parts = []
    if ops_total is not None:
        footer_parts.append(f"{int(ops_total):,} ops")
    if duration_ms is not None:
        footer_parts.append(f"{float(duration_ms):.1f} ms")
    footer = " | ".join(footer_parts) if footer_parts else "Generated by cache_bench"

    row_height = 30
    table_top = 162
    width = 920
    left = 34
    table_width = width - (left * 2)
    height = table_top + ((len(scenarios) + 2) * row_height) + 36

    columns = [
        ("scenario", left + 16, "start"),
        ("ops/s", left + 342, "end"),
        ("p50 ms", left + 448, "end"),
        ("p99 ms", left + 552, "end"),
        ("errors", left + 660, "end"),
        ("coalesce", left + 778, "end"),
    ]

    rows: list[str] = []
    rows.append(
        f'  <rect x="{left}" y="{table_top}" width="{table_width}" height="{row_height}" rx="10" fill="#0b1220" stroke="#334155" />'
    )
    for label, x, anchor in columns:
        rows.append(
            f'  <text x="{x}" y="{table_top + 20}" fill="#93c5fd" font-size="12" font-family="Verdana, sans-serif" font-weight="bold" text-anchor="{anchor}">{html.escape(label)}</text>'
        )
    rows.append(
        f'  <text x="{left + 852}" y="{table_top + 20}" fill="#93c5fd" font-size="12" font-family="Verdana, sans-serif" font-weight="bold" text-anchor="end">status</text>'
    )

    for index, scenario in enumerate(scenarios):
        name = str(scenario.get("name", "unknown"))
        row_y = table_top + row_height * (index + 1)
        row_fill = "#111827" if index % 2 == 0 else "#0f172a"
        rows.append(
            f'  <rect x="{left}" y="{row_y}" width="{table_width}" height="{row_height}" rx="8" fill="{row_fill}" stroke="#1f2937" />'
        )
        rows.append(
            f'  <text x="{left + 16}" y="{row_y + 20}" fill="#e2e8f0" font-size="12" font-family="Verdana, sans-serif">{html.escape(name)}</text>'
        )

        ops_value = _format_ops(float(scenario.get("ops_per_sec", 0.0)))
        p50_value = _format_ms(float(scenario.get("p50_ms", 0.0)))
        p99_value = _format_ms(float(scenario.get("p99_ms", 0.0)))
        err_value = _format_pct(float(scenario.get("error_rate", 0.0)))
        coalesce_value = _format_pct(float(scenario.get("coalescing_hit_ratio", 0.0)))
        rows.append(
            f'  <text x="{left + 342}" y="{row_y + 20}" fill="#e2e8f0" font-size="12" font-family="Verdana, sans-serif" text-anchor="end">{html.escape(ops_value)}</text>'
        )
        rows.append(
            f'  <text x="{left + 448}" y="{row_y + 20}" fill="#e2e8f0" font-size="12" font-family="Verdana, sans-serif" text-anchor="end">{html.escape(p50_value)}</text>'
        )
        rows.append(
            f'  <text x="{left + 552}" y="{row_y + 20}" fill="#e2e8f0" font-size="12" font-family="Verdana, sans-serif" text-anchor="end">{html.escape(p99_value)}</text>'
        )
        rows.append(
            f'  <text x="{left + 660}" y="{row_y + 20}" fill="#e2e8f0" font-size="12" font-family="Verdana, sans-serif" text-anchor="end">{html.escape(err_value)}</text>'
        )
        rows.append(
            f'  <text x="{left + 778}" y="{row_y + 20}" fill="#e2e8f0" font-size="12" font-family="Verdana, sans-serif" text-anchor="end">{html.escape(coalesce_value)}</text>'
        )

        status = str(scenario.get("status", "unknown"))
        status_fill, status_text = _status_style(status)
        status_x = left + 800
        rows.append(
            f'  <rect x="{status_x}" y="{row_y + 7}" width="52" height="16" rx="8" fill="{status_fill}" />'
        )
        rows.append(
            f'  <text x="{status_x + 26}" y="{row_y + 19}" fill="{status_text}" font-size="10" font-family="Verdana, sans-serif" text-anchor="middle" font-weight="bold">{html.escape(status.upper())}</text>'
        )

    table_title_y = 142

    svg = f"""<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{width}\" height=\"{height}\" viewBox=\"0 0 {width} {height}\">
  <defs>
    <linearGradient id=\"bg\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\">
      <stop offset=\"0%\" stop-color=\"#0f172a\" />
      <stop offset=\"100%\" stop-color=\"#1e293b\" />
    </linearGradient>
  </defs>
  <rect width=\"{width}\" height=\"{height}\" rx=\"18\" fill=\"url(#bg)\" />
  <text x=\"34\" y=\"44\" fill=\"#f8fafc\" font-size=\"22\" font-family=\"Verdana, sans-serif\" font-weight=\"bold\">Distributed Cache Benchmarks</text>
  <text x=\"34\" y=\"78\" fill=\"#38bdf8\" font-size=\"38\" font-family=\"Verdana, sans-serif\" font-weight=\"bold\">{html.escape(ops_label)}</text>
  <text x=\"34\" y=\"102\" fill=\"#e2e8f0\" font-size=\"14\" font-family=\"Verdana, sans-serif\">Global Throughput (ops/sec)</text>
  <text x=\"420\" y=\"78\" fill=\"#fbbf24\" font-size=\"34\" font-family=\"Verdana, sans-serif\" font-weight=\"bold\">{html.escape(p99_label)}</text>
  <text x=\"420\" y=\"102\" fill=\"#e2e8f0\" font-size=\"14\" font-family=\"Verdana, sans-serif\">Global p99 latency</text>
  <text x=\"34\" y=\"122\" fill=\"#94a3b8\" font-size=\"12\" font-family=\"Verdana, sans-serif\">{html.escape(footer)}</text>
  <text x=\"34\" y=\"{table_title_y}\" fill=\"#f1f5f9\" font-size=\"16\" font-family=\"Verdana, sans-serif\" font-weight=\"bold\">Scenario Scoreboard</text>
{chr(10).join(rows)}
</svg>
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(svg)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
