#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path


def _format_ops(value: float) -> str:
    if value >= 1_000_000_000:
        return f"{value / 1_000_000_000:.2f}B"
    if value >= 1_000_000:
        return f"{value / 1_000_000:.2f}M"
    if value >= 1_000:
        return f"{value / 1_000:.2f}K"
    return f"{value:.0f}"


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: bench/render_svg.py <input.json> <output.svg>", file=sys.stderr)
        return 1

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    data = json.loads(input_path.read_text())
    ops_per_sec = data.get("ops_per_sec")
    p99_ms = data.get("p99_ms")
    if ops_per_sec is None or p99_ms is None:
        raise SystemExit("Input JSON must include ops_per_sec and p99_ms")

    ops_label = _format_ops(float(ops_per_sec))
    p99_label = f"{float(p99_ms):.3f} ms"
    duration_ms = data.get("duration_ms")
    ops_total = data.get("ops_total")

    footer_parts = []
    if ops_total is not None:
        footer_parts.append(f"{int(ops_total):,} ops")
    if duration_ms is not None:
        footer_parts.append(f"{float(duration_ms):.1f} ms")
    footer = " · ".join(footer_parts) if footer_parts else "Generated by cache_bench"

    svg = f"""<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"640\" height=\"180\" viewBox=\"0 0 640 180\">
  <defs>
    <linearGradient id=\"bg\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\">
      <stop offset=\"0%\" stop-color=\"#0f172a\" />
      <stop offset=\"100%\" stop-color=\"#1e293b\" />
    </linearGradient>
  </defs>
  <rect width=\"640\" height=\"180\" rx=\"16\" fill=\"url(#bg)\" />
  <text x=\"32\" y=\"48\" fill=\"#f8fafc\" font-size=\"20\" font-family=\"Verdana, sans-serif\">Distributed Cache Benchmarks</text>
  <text x=\"32\" y=\"92\" fill=\"#38bdf8\" font-size=\"36\" font-family=\"Verdana, sans-serif\" font-weight=\"bold\">{ops_label}</text>
  <text x=\"32\" y=\"124\" fill=\"#e2e8f0\" font-size=\"16\" font-family=\"Verdana, sans-serif\">ops/sec</text>
  <text x=\"360\" y=\"92\" fill=\"#fbbf24\" font-size=\"32\" font-family=\"Verdana, sans-serif\" font-weight=\"bold\">{p99_label}</text>
  <text x=\"360\" y=\"124\" fill=\"#e2e8f0\" font-size=\"16\" font-family=\"Verdana, sans-serif\">p99 latency</text>
  <text x=\"32\" y=\"156\" fill=\"#94a3b8\" font-size=\"12\" font-family=\"Verdana, sans-serif\">{footer}</text>
</svg>
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(svg)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
